DROP DATABASE IF EXISTS bet;
CREATE DATABASE bet CHARACTER SET utf8;
USE bet;

CREATE TABLE bet.user (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR (25) NOT NULL,
    mail VARCHAR (50) NOT NULL,
    name VARCHAR (25) NOT NULL,
    surname VARCHAR (25) NOT NULL,
    password VARCHAR (512) NOT NULL
);